### ISSUE TITLE
t.setConfig is not a function

### ISSUE THREAD

**Issue by raphaelbleier** [jimz011/homekit-infused#107]
Hello, i do have a error on the startup page everytime and after some time it is disappearing pls help me.  

**Error**
```
type: custom:swipe-card
parameters:
  allowTouchMove: true
  grabCursor: true
  autoplay:
    disableOnInteraction: false
cards:
  - type: conditional
    conditions:
      - entity: input_boolean.dummy1
        state_not: dummy
    card:
      type: custom:button-card
      style: |
        ha-card {
          margin-top: -5px;
        }
      name: Insert Notification, please open user/notifications.yaml
      icon: mdi:alert
      size: 100%
      entity: input_boolean.dummy1
      show_state: false
      show_label: false
      layout: icon_name
      show_icon: true
      double_tap_action:
        action: navigate
        navigation_path: /homekit-infused/ha_settings
        haptic: light
      tap_action:
        action: more-info
        haptic: heavy
      styles:
        card:
          - '--ha-card-background': rgba(0,0,0,0.0)
          - box-shadow: none
          - height: 45px
          - width: 350px
        name:
          - font-size: var(--subtitle-font-size)
          - font-family: var(--font-family)
          - color: var(--subtitle-text-color)
          - justify-self: start
          - padding-left: 0px
          - font-weight: var(--subtitle-font-weight)
        grid:
          - grid-template-areas: '"i n"'
          - grid-template-columns: 8% 1fr
          - grid-template-rows: 1fr
        icon:
          - color: var(--subtitle-text-color)
          - padding-bottom: 3px
      state:
        - value: 'off'
          spin: false
```

**And the Code**
```
# This is the notifications page, you can edit notifications that are
# shown on the frontend in this file. This works with conditional cards.
# What this means is that the conditions need to be be met before these
# cards are shown. When there are more entities/states in a conditional
# card it will always be an 'AND' condition, it will never be an 'OR'
# condition. Edit the conditions, entities and notification content to
# your own likings.

# MAKE SURE YOU HAVE AT LEAST ONE NOTIFICATION OR YOU WILL GET AN ERROR.
# IF YOU DON'T WANT TO USE NOTIFICATIONS TURN IT OFF IN THE SETTINGS!

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #

# Card Config

# Example Config (You can uncomment this and edit it to your likings, if you want multiple notifications you can simply continue writing a new card below)

#- type: conditional
#  conditions:
#    - entity: binary_sensor.smoke_sensor
#      state: "off"
#    - entity: binary_sensor.front_door
#      state: "off"
#    - entity: vacuum.xiaomi_vacuum_cleaner
#      state: "docked"
#    - entity: binary_sensor.bedroom_door
#      state: "off"
#    - entity: sensor.dishwasher_status
#      state_not: "Clean"
#  card:
#    !include
#    - '../hki-base/templates/header/notification-template.yaml'
#    - icon: mdi:check-box-outline
#      name: All clear, there are no notifications.

#- type: conditional
#  conditions:
#    - entity: binary_sensor.smoke_sensor
#      state: "on"
#  card:
#    !include
#    - '../hki-base/templates/header/notification-template.yaml'
#    - icon: mdi:check-box-outline
#      name: Smoke detected in the Kitchen!

- type: conditional
  conditions:
    - entity: input_boolean.dummy1
      state_not: "dummy"
  card:
    !include
    - '../hki-base/templates/header/notification-template.yaml'
    - icon: mdi:alert
      name: 'Insert Notification, please open user/notifications.yaml'
```

Some Help would be nice !
