### ISSUE TITLE
How to incorporate addons with other views

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#112]
Hi

I really liked the new energy dashboard, however i made this already. It measures current consumption in watt, and all the most used devices, and uses graph. I want to incorporate this

```
  my_view:
    energy:
      - type: energy-date-selection
      - type: energy-usage-graph
      - type: energy-distribution
      - type: energy-devices-graph
```
      
But i cant make it work, it stays at the bottom of the view, but i need to be displayed at the start, do you have any help for you?

```
######## ENERGI ##############################
  energi:
    subtitle: "[[[ return `Akkurat nå ligger forbruket på ${states['sensor.power_bjorganveien_39'].state} W`; ]]]"
    layout:
      max_cols: 3
    columns:
      buttons: 4
      graphs: 2
    icon: mdi:chart-line
    show_in_favorites: true
    show_in_menu: false
    button_badge: sensor.power_bjorganveien_39
    button_label: "[[[ return `Kostnad i dag: ${states['sensor.kostnad_strom_avrundet'].state} kr`; ]]]"
    graphs:
      - title: Oversikt
        entities:
          - entity: sensor.power_bjorganveien_39
            hours_to_show: 72
            line_color: green
            line_width: 3
          - entity: sensor.accumulated_consumption_bjorganveien_39
            line_color: orange
            line_width: 3
          - entity: sensor.accumulated_cost_bjorganveien_39
            line_color: red
            line_width: 3
      - title: Watt
        line_color: purple
        line_width: 3
        entities:
          - sensor.vvb_vaskerom_power
          - sensor.vaskemaskin_vaskerom_power
          #  - sensor.avfukter_kjellerstue_power
          - sensor.tv_hifi_stue_power
          - sensor.kjoleskap_kjokken_power
          - sensor.oppvaskmaskin_kjokken_power
          - sensor.gulvvarme_bad_electric_consumed_w
          - sensor.gulvvarme_matheo_electric_consumed_w
          - sensor.gulvvarme_pabygg_electric_consumed_w
          - sensor.gulvvarme_emma_electric_consumed_w
          - sensor.gulvvarme_gang_electric_consumed_w
      - title: Volt
        line_color: cyan
        line_width: 3
        entities:
          - sensor.voltage_phase1_bjorganveien_39
          - sensor.voltage_phase2_bjorganveien_39
          - sensor.voltage_phase3_bjorganveien_39
      - title: Strøm
        line_color: dodgerblue
        line_width: 3
        entities:
          - sensor.current_l1_bjorganveien_39
          - sensor.current_l2_bjorganveien_39
          - sensor.current_l3_bjorganveien_39
```

**Comment by jimz011** [comment]
Uhm, could you send a screenshot maybe?

I will change the position of the energy cards and graphs with the current addons. However starting this weekend you can put any card in any position you want using the new custom addon (which will be released this weekend).

This will make it so that you can use any card ever designed for HA, this includes official and custom cards. They can all be added to the view_config just like normal lovelace would. This will remove all the current custom_cards addons in the near future since that will no longer be necessary, also the new custom addon is so nice that it uses less than half of the code used for the current custom_cards addon.

**Comment by henrikrox** [comment]
> 
![2021-12-02 17_54_08-Homekit Infused - Home Assistant](https://user-images.githubusercontent.com/6884716/144467318-49f42617-f2e5-4ea0-b841-6a0e583ed355.png)
Heres what i used before, code is the second in the original op

i tried using the energy addon
![2021-12-02 17_54_28-Homekit Infused - Home Assistant](https://user-images.githubusercontent.com/6884716/144467466-5bb65f18-01c0-4e67-a3ba-d6c58bde662b.png)

However when i try to incorporate them togehter, the energy addon always goes to the bottom. even though the code is at the top of the room

```
######## ENERGI #############################################################################################################
  energi:
    energy:
      - type: energy-date-selection
      - type: energy-usage-graph
      - type: energy-distribution
      - type: energy-devices-graph
    subtitle: "[[[ return `Akkurat nå ligger forbruket på ${states['sensor.power_bjorganveien_39'].state} W`; ]]]"
    layout:
      max_cols: 3
    columns:
      buttons: 4
      graphs: 2
    icon: mdi:chart-line
    show_in_favorites: true
    show_in_menu: false
    button_badge: sensor.power_bjorganveien_39
    button_label: "[[[ return `Kostnad i dag: ${states['sensor.kostnad_strom_avrundet'].state} kr`; ]]]"
    graphs:
      - title: Oversikt
        entities:
          - entity: sensor.power_bjorganveien_39
            hours_to_show: 72
            line_color: green
            line_width: 3
          - entity: sensor.accumulated_consumption_bjorganveien_39
            line_color: orange
            line_width: 3
          - entity: sensor.accumulated_cost_bjorganveien_39
            line_color: red
            line_width: 3
      - title: Watt
        line_color: purple
        line_width: 3
        entities:
          - sensor.vvb_vaskerom_power
          - sensor.vaskemaskin_vaskerom_power
          #  - sensor.avfukter_kjellerstue_power
          - sensor.tv_hifi_stue_power
          - sensor.kjoleskap_kjokken_power
          - sensor.oppvaskmaskin_kjokken_power
          - sensor.gulvvarme_bad_electric_consumed_w
          - sensor.gulvvarme_matheo_electric_consumed_w
          - sensor.gulvvarme_pabygg_electric_consumed_w
          - sensor.gulvvarme_emma_electric_consumed_w
          - sensor.gulvvarme_gang_electric_consumed_w
      - title: Volt
        line_color: cyan
        line_width: 3
        entities:
          - sensor.voltage_phase1_bjorganveien_39
          - sensor.voltage_phase2_bjorganveien_39
          - sensor.voltage_phase3_bjorganveien_39
      - title: Strøm
        line_color: dodgerblue
        line_width: 3
        entities:
          - sensor.current_l1_bjorganveien_39
          - sensor.current_l2_bjorganveien_39
          - sensor.current_l3_bjorganveien_39
  ######## SECURITY #############################################################################################################
  Sikkerhet:
    subtitle: "[[[ return `Alarmen er ${states['alarm_control_panel.home_alarm'].state}`; ]]]"
    columns:
      cameras: 1
      buttons: 3
    icon: mdi:cctv
    show_in_favorites: true
    show_in_menu: false
    button_badge: sensor.current_binary_sensors_on
    button_label: "[[[ return `Alarmen er ${states['alarm_control_panel.home_alarm'].state}`; ]]]"
    devices:
      - title: Bevegelse
        entities:
          - binary_sensor.brannvarsler_matheo_home_security_motion_detection
          - binary_sensor.brannvarsler_emma_home_security_motion_detection
      - title: Brannvarsler
        entities:
          - binary_sensor.brannvarsler_matheo_smoke_alarm_smoke_detected
          - binary_sensor.brannvarsler_emma_smoke_alarm_smoke_detected
```
