### ISSUE TITLE
Layout error with some addons

### ISSUE THREAD

**Issue by jjsapido** [jimz011/homekit-infused#118]
I'm trying to understand if the following behavior is related to my configuration or there's a bug:

home view configuration as follow:

```
  home:
    layout:
      type: custom:vertical-layout
      max_cols: 1
```

if I add addon like: _persons_, _custom_, _hki_menu_, everything work fine, i.e., i have a vertical 1-column layout

However, as soon as I add a single _climate_ or _devices_ addon (for instance, I didn't test with all addons) the layout change to masonry

**Comment by jimz011** [comment]
Well the documentation is quite different from your example, so please read it again, the config you posted will do absolutely nothing 😊

**Comment by jjsapido** [comment]
Thanks, very true, now it works, changed to:

```
    layout:
      type: custom:vertical-layout
      options:
        - max_cols: 1
          max_width: 1000
```

I didn't understood at first
