### ISSUE TITLE
Thermostat addon not displaying thermostat

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#127]
I followed the docs I swear as close as possible but for some reason the climate addon seems to not be working.

Can you tell me what I did wrong, please?

My code is in the screenshots:

<img width="371" alt="Screen Shot 2022-02-13 at 8 09 24 PM" src="https://user-images.githubusercontent.com/3034555/153784511-3f85b96b-ca23-4919-9756-fdb1990c8457.png">

My Code:

<img width="586" alt="Screen Shot 2022-02-13 at 8 09 14 PM" src="https://user-images.githubusercontent.com/3034555/153784512-53cbdff7-0bd3-4344-83eb-2f6b931dc190.png">

**Comment by jimz011** [comment]
The indentations are off, try this, also you have misspelled entities

```yaml
- title: Test Space 3
  climate:
    controls:
      title: Thermostat Controls
    thermostats:
      - title: Nest Thermostat
        entities:
          - entity: climate.3family_room
            lock: true
          - entity: climate.3family_room
            ambient_temperature: sensor.3family_room_temperature
```

**Comment by dnestico** [comment]
So I copied/pasted your code and that still didn't fix it unfortunately but that might be due to weird copying/pasting formatting, it basically gave me the error and wouldn't let me save the file as normally what happens. 

So this is the code I copied/pasted, for some reason did not work:

<img width="585" alt="Screen Shot 2022-02-15 at 12 28 33 AM" src="https://user-images.githubusercontent.com/3034555/153998935-b4f6aecb-98d4-4daa-bd25-527ef736f44c.png">

And to make things easier I've included my view_config.yaml file here too, if possible can you put the widget in the "Main Room please:

[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8066103/ezyzip.zip)

**Comment by jimz011** [comment]
The indentation is still wrong, yaml always uses 2 spaces.
So you have done this:
```yaml
thermostats:
     - title: Nest Thermostat
       entities:
         - entity: climate.3family_room
           lock: true
         - entity: climate.3family_room
           ambient_temperature: sensor.3family_room_temperature
 ```
 But that means a 5 spaces indent. You should never use more than 2! Try it like the option below.

```yaml
thermostats:
  - title: Nest Thermostat
    entities:
      - entity: climate.3family_room
        lock: true
      - entity: climate.3family_room
        ambient_temperature: sensor.3family_room_temperature
 ```

I could have just changed your file, but I would rather that you understand what you did wrong as all addons work in a similar way (it's even more consistent in HKI 5). Learning how to use YAML will certainly help you create even more awesome stuff in lovelace.
