### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#132]
Hi I followed the guide on the camera addon (https://jimz011.github.io/homekit-infused/addons-v4/cameras.html), I wanted to make it so the cameras show horizontally in a group so I did what it said at the bottom and it did technically work, it's just how do I get rid of that other error on the screen now? I got what I wanted but at the same time it came with that error I did not want of course.. pls help!

The error:

<img width="770" alt="Screen Shot 2022-02-24 at 3 01 43 AM" src="https://user-images.githubusercontent.com/3034555/155483272-8fce9e02-9892-4ed6-9add-d2fe0d400e7f.png">

My code:

<img width="337" alt="Screen Shot 2022-02-24 at 3 01 58 AM" src="https://user-images.githubusercontent.com/3034555/155483333-174797cf-1f72-4315-ab6e-fff1823657e4.png">

If needed, my view_config:

[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8130718/ezyzip.zip)

**Comment by jimz011** [comment]
you defined a new list in your first card:

```yaml
# try this

cameras:
  - title: WYZE Cameras
    columns: 2
    entities: # Look at this line in your own config, it has a hyphen at the start depicting a new item in the list!
      - entity: camera.ffmpeg
        camera_view: live # this must be either auto or live
  - entities:
      - entity: camera.ffmpeg_2
        camera_view: live
```

Also I will not recommend using the `camera_view: live` feature as it is very resource heavy!

**Comment by dnestico** [comment]
Can it not be done with 4 cameras? I've corrected the code as you said and the error code is gone which is great but it looks like this now:

What it looks like: (the cameras are fine I just took a screenshot before they loaded)

<img width="1440" alt="Screen Shot 2022-02-24 at 6 47 45 PM" src="https://user-images.githubusercontent.com/3034555/155626564-c10174d3-da9b-421b-993f-f36e5666ba2f.png">

My code based off yours: (I will change live to auto soon, just like it the way it is now on live)

<img width="311" alt="Screen Shot 2022-02-24 at 6 48 21 PM" src="https://user-images.githubusercontent.com/3034555/155626586-57adb447-114c-435b-9454-1ed002870d23.png">


view_config file for a clearer view for you:

[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8137314/ezyzip.zip)

**Comment by jimz011** [comment]
try this:

```yaml
    layout:
      layout_type: custom:horizontal-layout
      layout:
        options:
          - max_cols: 4
 ```

**Comment by jimz011** [comment]
I know it is a bit weird, I fixed this in HKI 5, but for now that is the way to go

**Comment by dnestico** [comment]
Yea this is definitely weird... any temporary way to make them all together like a group until HKI5, like 2 cameras at the top, 2 at the bottom? Like I was trying to do from original pic.

My code based of yours:

<img width="355" alt="Screen Shot 2022-02-24 at 7 07 02 PM" src="https://user-images.githubusercontent.com/3034555/155628368-f1c3d644-8dd3-43f2-ae32-d88a793be7e1.png">

The result:

<img width="1388" alt="Screen Shot 2022-02-24 at 7 07 15 PM" src="https://user-images.githubusercontent.com/3034555/155628391-1e6c2590-4646-48a1-ad23-0f997cbba0ae.png">

**Comment by jimz011** [comment]
well, two top, two bottom should be easy enough:

```yaml
    cameras:
      - title: Inside Camera's
        entities:
          - camera.ffmpeg_1
          - camera.ffmpeg_2
      - title: Outside Camera's
        entities:
          - camera.ffmpeg_3
          - camera.ffmpeg_4
```
