### ISSUE TITLE
Addons are not showing on the home menu

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#143]
Sample code

```
views: # NEVER REMOVE THIS LINE
  # Home
  home:
    title: greeting
    show_in_navbar: true
    show_in_menu: false
    icon: mdi:home
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      weather:
        - title: hide
          type: simple_weather
          entity: weather.home
          city_name: Vanvikan
      picture_elements:
        - title: hide
          columns: 2
          cards:
            - image: /local/images/carina.jpeg
              elements: !include ../elements/frontpage-photo-carina.yaml
            - image: /local/images/henrikv2.jpeg
              elements: !include ../elements/frontpage-photo-henrik.yaml

  ### Carina ###
  carina:
    title: Carina
    subtitle: "[[[ return `${states['sensor.carina_sin_iphone_geocoded_location'].state}`; ]]]"
    button_badge: person.carina
    show_in_menu: false
    icon: mdi:human-female
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      #calendar:
       # - title: Calendar
        #  entities:
         #   - calendar.stephanie
      map:
        - title: Location Carina
          default_zoom: 15
          aspect_ratio: 16x10
          entities:
            - person.carina

  ### Henrik ###
  henrik:
    title: Henrik
    subtitle: "[[[ return `${states['sensor.henrik_iphone_geocoded_location'].state}`; ]]]"
    button_badge: person.henrik
    show_in_menu: false
    icon: mdi:human-male
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      #calendar:
       # - title: Calendar
        #  initial_view: dayGridDay
         # entities:
          #  - calendar.jimmy
      map:
        - title: Location Henrik
          default_zoom: 15
          aspect_ratio: 16x10
          entities:
            - person.henrik

# Weather
  weather:
    subtitle: "[[[ return `${states['weather.home'].state}`; ]]]"
    button_badge: sensor.varmepumpe_stue_outside_temperature
    icon: mdi:weather-partly-cloudy
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      weather:
        - type: core
          entity: weather.home
          city_name: Vanvikan
   #   air_visual:
    #    - air_pollution_level: sensor.u_s_air_pollution_level
     #     air_quality_index: sensor.u_s_air_quality_index
      #    main_pollutant: sensor.u_s_main_pollutant
       #   city_name: Vanvikan

      sun_card:
        - show_elevation: true 
          title: Soloppgang og solnedgang
     # meteoalarm:
      # - entity: binary_sensor.meteoalarm
      iframe:
        - url: https://embed.windy.com/

      custom:
          - title: Utendørstemperatur siste 6 måneder
            cards:
              - type: custom:apexcharts-card
                graph_span: 6month
                update_interval: 2h
                experimental:
                  color_threshold: true
                series:
                  - entity: sensor.varmepumpe_stue_outside_temperature
                    curve: smooth
                    group_by:
                      duration: 2h
                      func: avg
                    color_threshold:
                      - value: -10
                        color: blue
                        opacity: 1
                      - value: 0
                        color: cyan
                      - value: 15
                        color: green
                      - value: 25
                        color: orange
                    stroke_width: 1
  # Menu
  menu:
    title: Menu
    show_in_navbar: true
    show_in_menu: false
    subtitle: "[[[ return `HKI 5 v.${states['sensor.hki_current_version'].state}`; ]]]"
    icon: mdi:apps
    addons:
      favorites:
        - title: Favorites
      menu:
        - title: Menu

  # Add your own views below this line!

          
# Lights Ground Floor
  lights:
    title: Lights
    subtitle: "[[[ if (states['sensor.current_lights_on'].state == 0) return `All lights are turned off`; if (states['sensor.current_lights_on'].state == 1) return `1 light is turned on`; else return `${states['sensor.current_lights_on'].state} lights are turned on`; ]]]"
    icon: mdi:floor-lamp
    show_in_favorites: true
    show_in_menu: false
    button_badge: sensor.current_lights_on
    button_label: "[[[ if (states['sensor.current_lights_on'].state == 0) return `Lights Off`; else return `${states['sensor.current_lights_on'].state} Lights On`; ]]]"
    view_selector:
      columns: 3
      aspect_ratio: 3/1
      size: 15%
      elements:
        - icon: mdi:home-floor-b
          path: lights_1
          name: Basement
        - icon: mdi:home-floor-g
          path: lights
          this_view: true
          name: Ground Floor
        - icon: mdi:theme-light-dark
          path: lights_2
          name: Adaptive
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      button:
        # Small Screens
        - title: Woonkamer
          entities:
            - light.plafond
            - light.eettafel
            - entity: light.woonkamer_led_lampen
              type: rgb
            - entity: light.tafellamp
              type: color-temp
            - entity: light.vloerlamp
              type: color-temp
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Slaapkamer
          lock: true
          entities:
            - entity: light.nachtkastje_stephanie
              type: color-temp
            - entity: light.nachtkastje_jimmy
              type: color-temp
            - entity: light.nachtkastjes
              type: color-temp
            - entity: light.slaapkamer_led_lampen
              type: rgb
            - light.bed_lamp
            - light.kast_lamp
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Kleine Kamer
          entities:
            - entity: light.office_led_lampen
              type: rgb
            - entity: light.kleine_kamer
              type: color-temp
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Keuken
          entities:
            - entity: light.keuken
              type: color-temp
            - entity: light.keuken_leds
              type: rgb
            - entity: light.keuken_leds_onder
              type: rgb
            - entity: light.keuken_led_lampen
              type: rgb
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Bijkeuken
          entities:
            - light.bijkeuken
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Gang
          entities:
            - light.entree_lamp
            - light.gang_lamp
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Balkon
          entities:
            - light.balkon
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Badkamer
          entities:
            - light.koogeek_sw_056ce9
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        - title: Toilet
          entities:
            - light.toilet
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        # Larger Screens
        - title: Woonkamer
          entities:
            - light.plafond
            - light.eettafel
            - entity: light.woonkamer_led_lampen
              type: rgb
            - entity: light.tafellamp
              type: color-temp
            - entity: light.vloerlamp
              type: color-temp
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Slaapkamer
          lock: true
          entities:
            - entity: light.nachtkastje_stephanie
              type: color-temp
            - entity: light.nachtkastje_jimmy
              type: color-temp
            - entity: light.nachtkastjes
              type: color-temp
            - entity: light.slaapkamer_led_lampen
              type: rgb
            - light.bed_lamp
            - light.kast_lamp
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Kleine Kamer
          entities:
            - entity: light.office_led_lampen
              type: rgb
            - entity: light.kleine_kamer
              type: color-temp
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Keuken
          entities:
            - entity: light.keuken
              type: color-temp
            - entity: light.keuken_leds
              type: rgb
            - entity: light.keuken_leds_onder
              type: rgb
            - entity: light.keuken_led_lampen
              type: rgb
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Bijkeuken
          entities:
            - light.bijkeuken
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Gang
          entities:
            - light.entree_lamp
            - light.gang_lamp
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Balkon
          entities:
            - light.balkon
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Badkamer
          entities:
            - light.koogeek_sw_056ce9
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4
        - title: Toilet
          entities:
            - light.toilet
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4

# Lights Basement
  lights_1:
    title: Lights
    subtitle: "[[[ if (states['sensor.current_lights_on'].state == 0) return `All lights are turned off`; if (states['sensor.current_lights_on'].state == 1) return `1 light is turned on`; else return `${states['sensor.current_lights_on'].state} lights are turned on`; ]]]"
    icon: mdi:floor-lamp
    show_in_menu: false
    button_badge: sensor.current_lights_on
    button_label: "[[[ if (states['sensor.current_lights_on'].state == 0) return `Lights Off`; else return `${states['sensor.current_lights_on'].state} Lights On`; ]]]"
    view_selector:
      columns: 3
      aspect_ratio: 3/1
      size: 15%
      elements:
        - icon: mdi:home-floor-b
          path: lights_1
          name: Basement
          this_view: true
        - icon: mdi:home-floor-g
          path: lights
          name: Ground Floor
        - icon: mdi:theme-light-dark
          path: lights_2
          name: Adaptive
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      button:
        # Small Screens
        - title: Berging
          entities:
            - entity: light.berging
              type: color-temp
          view_layout:
            show:
              mediaquery: "(max-width: 350px)"
          columns: 3
        # Larger Screens
        - title: Berging
          entities:
            - entity: light.berging
              type: color-temp
          view_layout:
            show:
              mediaquery: "(min-width: 350px)"
          columns: 4

# Adaptive Lighting
  lights_2:
    title: Lights
    subtitle: "[[[ if (states['sensor.current_lights_on'].state == 0) return `All lights are turned off`; if (states['sensor.current_lights_on'].state == 1) return `1 light is turned on`; else return `${states['sensor.current_lights_on'].state} lights are turned on`; ]]]"
    icon: mdi:floor-lamp
    show_in_menu: false
    button_badge: sensor.current_lights_on
    button_label: "[[[ if (states['sensor.current_lights_on'].state == 0) return `Lights Off`; else return `${states['sensor.current_lights_on'].state} Lights On`; ]]]"
    view_selector:
      columns: 3
      aspect_ratio: 3/1
      size: 15%
      elements:
        - icon: mdi:home-floor-b
          path: lights_1
          name: Basement
        - icon: mdi:home-floor-g
          path: lights
          name: Ground Floor
        - icon: mdi:theme-light-dark
          path: lights_2
          name: Adaptive
          this_view: true
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px
    addons:
      button:
        - title: Woonkamer
          entities:
            - entity: switch.adaptive_lighting_livingroom_leds
              name: LEDs
            - entity: switch.adaptive_lighting_livingroom_lights
              name: Lampen
        - title: Kleine Kamer
          entities:
            - entity: switch.adaptive_lighting_office_leds
              name: LEDs
            - entity: switch.adaptive_lighting_office_lights
              name: Lampen
        - title: Slaapkamer
          entities:
            - entity: switch.adaptive_lighting_bedroom_leds
              name: LEDs
            - entity: switch.adaptive_lighting_bedroom_lights
              name: Lampen
        - title: Keuken
          entities:
            - entity: switch.adaptive_lighting_kitchen_leds
              name: LEDs
            - entity: switch.adaptive_lighting_kitchen_lights
              name: Lampen
            - entity: switch.adaptive_lighting_kitchen_workspace
              name: Aanrecht
        - title: Bijkeuken
          entities:
            - entity: switch.adaptive_lighting_laundry
              name: Lamp
        - title: Balkon
          entities:
            - entity: switch.adaptive_lighting_outside
              name: Lamp
        - title: Toilet
          entities:
            - entity: switch.adaptive_lighting_toilet
              name: Lamp
        - title: Berging
          entities:
            - entity: switch.adaptive_lighting_berging
              name: Lamp
```

![Screenshot 2022-04-06 at 09 06 27](https://user-images.githubusercontent.com/6884716/161915667-2489a43e-1f06-45fc-b49f-48427be30f50.png)
![Screenshot 2022-04-06 at 09 06 31](https://user-images.githubusercontent.com/6884716/161915685-5b9d2845-805b-4a64-a6a0-a4f3c784baae.png)

Is this a change from v4 to v5?

Tried with other simple views also, but can't get any add-on to show up on the main screen.
