### ISSUE TITLE
Im confused on how lights are being shown as on/off

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#144]
![IMG_5542](https://user-images.githubusercontent.com/6884716/161936267-2b12cfcc-5154-4e68-af8d-f7f790b2ef9a.jpg)
Please help me understand why my smart bulbs is shown with a border, my switch lights in the middle right has another colour (brownish) and why my z-wave lights is just black :(

**Comment by henrikrox** [comment]
it gets very confusing for an end user, when the information is displayed in 3 different ways, how can I do it like in v4, that the just the mdi icon changes colours when its one, I don't need borders etc.

**Comment by henrikrox** [comment]
![Screenshot 2022-04-06 at 11 47 13](https://user-images.githubusercontent.com/6884716/161947780-1a8223eb-77af-4231-8362-40925fe8e84b.png)

this is from v4.

with v5

My rgb lights have box colour around them, same with color-temp.

all my wave dimmers, just show black, even with on, my switches, show yellow when on, and black when off. With v4 everything was correct also the dimmers turned yellow and black when off

**Comment by jimz011** [comment]
The box around the lights is just a shadow setting which can be easily turned off in the settings. As well as the icon active color.

I had just changed the default style, you can still get the original HKI 4 style by changing these settings. HKI 5 makes it possible to change colors on the fly, it also means that in the near future I will add new themes (I might add the HKI 4 theme for the people that prefer that)

**Comment by jimz011** [comment]
After next weeks update I will start creating some color schemes which should fix these issues for you. It is already possible, but requires a bit of tinkering in the theme settings.

The reason I added the color is because many people like the look of it, the color of the border is of the same color as the light is currently showing (so if your light is red, the border is also red).

You can turn this feature off by going to HKI Settings and set the lights box-shadow to `none`.

![image](https://user-images.githubusercontent.com/47046878/162065749-7484c189-7f7a-470d-854a-8e084072e538.png)

To get the same titles as in HKI 4, you can do the following:
![image](https://user-images.githubusercontent.com/47046878/162065944-898e3098-e7af-40aa-be72-d52bb2ef13b7.png)

And, to change the icon active color for all other lights, set it globally here:
![image](https://user-images.githubusercontent.com/47046878/162066048-8703aba9-6732-47c5-88b5-a0105aa79bf2.png)

I know it sucks if you were used to the colors of HKI 4 and it's themes. But I will add most themes back in, since it is super easy for me to create themes now. But you also gain the advantage to change the theme to your very own likings.

E.g.
![image](https://user-images.githubusercontent.com/47046878/162066282-fc8aa6e5-2742-4471-958f-2e0c0d0c07c2.png)
![image](https://user-images.githubusercontent.com/47046878/162066384-360c612d-42b1-4df2-925b-24e01d49f789.png)

For someone with OCD as you say, you can literally change the appearance to whatever suits your needs or mood.

Lastly, if you wish to restore the hki settings button in the menu you can add a button addon to your menu view and create a button that navigates to hki-settings. There should be very few limits this time around, though admittedly because of these 250+ new features it also means some things have gotten a bit more complicated.

I trust that with time you'll find that things are much more logical in HKI 5 (like placing the cards in your desired order, using grids or device specific cards). And if you used the custom_cards addon in HKI 4, you'll be happy to know that HKI 5 still includes that way of configuration but is just renamed to custom_legacy.

I'd love feedback, especially from long term users because without it I can't make HKI better. Most of the features have been added because they were requested, though designwise it mostly comes from my own point of view, which is why feedback is great! So I thank you for that.

One more thing... You mentioned something about other cards breaking when setting colors. If you mean within the custom addon then there is a simple solution (which should fit most cards fine).

```yaml
  my_view:
    title: My View
    addons:
      custom:
        - title: My stack
          cards:
            - type: markdown
              card_mod:
                class: hki
              content: Use card_mod in your custom cards and set the class to HKI, you can add styles yourself as well
            - type: markdown
              card_mod:
                class: hki
                style: |
                  ha-card {
                    box-shadow: none !important;
                  }
              content: Like this you can use the hki class and add more styling to the card. removing class hki can make you style the card yourself
```

I hope this information helps and maybe help you understand HKI 5 a bit better and hopefully you will achieve the HKI 4 look and feel without too much effort because of this information.
