### ISSUE TITLE
Bug with header and blinds/covers

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#145]
Think I have found a bug I have this code in config.yaml

```
  header:
    badges:
      - name: Thermostats
        icon: mdi:thermometer
        entity: sensor.current_climate_entities_on
        group_entity: group.all_climate_entities
        grid_area: six
      - name: Windows
        icon: mdi:blinds
        entity: sensor.current_covers_open
        group_entity: group.all_cover_entities
        grid_area: four
      - name: Garasje
        icon: mdi:garage
        entity: sensor.current_garage_doors_open
        group_entity: group.all_garage_door_entities
        grid_area: four
      - name: Motion
        icon: mdi:motion-sensor
        entity: sensor.current_binary_sensors_on
        group_entity: group.all_binary_sensor_entities
        grid_area: three
      - name: Devices
        icon: mdi:power-plug
        entity: sensor.current_devices_on
        group_entity: group.all_device_switch_entities
        grid_area: two
      - name: Lights
        icon: mdi:lightbulb
        entity: sensor.current_lights_on
        group_entity: group.al

```

![Screenshot 2022-04-06 at 16 09 59](https://user-images.githubusercontent.com/6884716/161994583-9bc7fbd1-08ea-4f55-b4de-30de54b989a1.png)

I check the sensor.current_covers_open and its listing 1 as open, but there is a huge gap in the header. How can I fix this?
