### ISSUE TITLE
Unknown type encountered: grid

### ISSUE THREAD

**Issue by janstadt** [jimz011/homekit-infused#146]
Hello. Im new to HKI but it looks awesome. Im running into an issue with one of my views stating that the grid type is unknown. This is my view:

```
  remotes:
    title: Remotes
    show_in_favorites: false
    show_in_navbar: true
    icon: mdi:remote
    addons:
      entities:
        - title: Remotes
          entities:
            - square: false
              columns: 1
              type: grid
              cards:
                - square: false
                  columns: 3
                  type: grid
                  cards:
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: master_bedroom
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: master_bedroom
                      name: Master Bedroom
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: living_room
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: living_room
                      name: Living Room
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: loft
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: loft
                      name: Loft
                - type: custom:state-switch
                  entity: input_select.roku_remote
                  states:
                    master_bedroom:
                      type: custom:roku-card
                      tv: true
                      name: Master Bedroom Remote
                      entity: remote.master_bedroom_roku
                    living_room:
                      type: custom:roku-card
                      name: Living Room Remote
                      entity: remote.roku
                      tv: true
                      volume_up:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku
                            command: volume_up
                      volume_down:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku
                            command: volume_down
                    loft:
                      type: custom:roku-card
                      name: Loft Remote
                      entity: remote.roku_express_4k
                      tv: true
                      volume_up:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku_express_4k
                            command: volume_up
                      volume_down:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku_express_4k
                            command: volume_down
 
```
This config renders correctly in lovelace like this:
![image](https://user-images.githubusercontent.com/1872087/162032329-3357a168-f7b3-499f-b8bd-e48c9c6e26b3.png)

Would anyone be able to help me out? When running through the config check it states everything is fine. Unsure what to do next. I saw some people talking about caching issues, but i've cleared my browser cache without any luck. TIA!

**Comment by jimz011** [comment]
![Screenshot_20220406-193107_GitHub.jpg](https://user-images.githubusercontent.com/47046878/162033832-c0590a36-f7f9-4033-97e4-81a338375b48.jpg)

You have setup the stack config twice. Remove the second and indent everything below correctly after doing so.

**Comment by janstadt** [comment]
Thanks for the quick reply @jimz011 Hmmm. I think (thought) thats on purpose. The first column is the outer container column, then there is another grid entity of 3 columns (which are the top buttons) followed by a state switch entity underneath which toggles each remote. Basically a grid inside a grid i guess. 
![image](https://user-images.githubusercontent.com/1872087/162036681-5df08e7f-3ac1-43a7-a148-20081c29f72a.png)
Same config and indentation in lovelace seems to work.

**Comment by jimz011** [comment]
ah, if you want to create your own cards use the custom addon instead.

Try it like this

```yaml
  remotes:
    title: Remotes
    show_in_favorites: false
    show_in_navbar: true
    icon: mdi:remote
    addons:
      custom:
        - title: Remotes
          cards:
            - square: false
              columns: 1
              type: grid
              cards:
                - square: false
                  columns: 3
                  type: grid
                  cards:
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: master_bedroom
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: master_bedroom
                      name: Master Bedroom
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: living_room
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: living_room
                      name: Living Room
                    - type: custom:button-card
                      entity: input_select.roku_remote
                      icon: mdi:remote
                      size: 50px
                      color: auto
                      state:
                        - value: loft
                          color: gold
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.roku_remote
                          option: loft
                      name: Loft
                - type: custom:state-switch
                  entity: input_select.roku_remote
                  states:
                    master_bedroom:
                      type: custom:roku-card
                      tv: true
                      name: Master Bedroom Remote
                      entity: remote.master_bedroom_roku
                    living_room:
                      type: custom:roku-card
                      name: Living Room Remote
                      entity: remote.roku
                      tv: true
                      volume_up:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku
                            command: volume_up
                      volume_down:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku
                            command: volume_down
                    loft:
                      type: custom:roku-card
                      name: Loft Remote
                      entity: remote.roku_express_4k
                      tv: true
                      volume_up:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku_express_4k
                            command: volume_up
                      volume_down:
                        tap_action:
                          action: call-service
                          service: remote.send_command
                          service_data:
                            entity_id: remote.roku_express_4k
                            command: volume_down
```
