### ISSUE TITLE
[Question] Regarding alternative tap Thermostats

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#149]
Prior to 2022.4.0 i changed the behaviour of thermostats in base folder here

hki-base/templates/button/thermostats.yaml

```
# card
type: custom:button-card
template: 
  - style-default
name: {{ name }}
aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "[[[ if (states['{{entity}}'].state == 'heat_cool') return `${states['{{entity}}'].attributes.target_temp_low}° - ${states['{{entity}}'].attributes.target_temp_high}°`; if (states['{{entity}}'].state == 'heat') return `${states['{{entity}}'].attributes.temperature}°`; if (states['{{entity}}'].state == 'cool') return `${states['{{entity}}'].attributes.temperature}°`; else return `--` ]]]"
lock:
  enabled: {{ lock|default('false') }}
  unlock: tap
show_icon: false
show_name: true
show_label: true
show_state: true
tap_action:
  action: more-info
```

I want when i tap the thermostat, more info comes up, not toggling it on or off.

From looking at release notes from 2022.4.0 this is now moved to configuration, however the possible options was not well documented

`You can reverse the default tap/hold action behaviour by setting action: alternative for this entire stack at once`

Whats the correct yaml representation here

```
  my_view:
    addons:
      thermostat:
         action: 
            tap: more-info 
```

or something?

**Comment by jimz011** [comment]
try this:

```yaml
  my_view:
    addons:
      thermostat:
        - title: My thermostats
          action: alternative
          entities:
            - climate.livingroom
```
