### ISSUE TITLE
Button card aspect ratio not working

### ISSUE THREAD

**Issue by Btje1977** [jimz011/homekit-infused#150]
When adding square off and then setting the aspect_ratio to 4/1 the card stays square and when column is 1 it is the full width and when column is removed  it is just as large as column is 3

![Screenshot_2022-04-20-16-44-14-38_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/23438853/164292151-1440700f-5601-4b47-8957-225a150bef7b.jpg)
![Screenshot_2022-04-20-16-45-19-32_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/23438853/164292163-34cbd26b-1562-41ed-87e3-9240f32184db.jpg)

**Comment by jimz011** [comment]
Actually, I've been going over the code and it seems that this wasn't a feature at all.
You could set the aspect_ratio, but only for individual buttons:

```yaml
addons:
  button:
    - title: Test
      entities:
        - entity: light.test
          aspect_ratio: 4/1
        - entity: light.test_2
          aspect_ratio: 2/1
```

Since it wasn't possible at all to set this for the entire stack at once, I have treated this as a feature request instead of a bug and will be added in 2022.4.1.

The code below shall work in that version
```yaml
addons:
  button:
    - title: Test
      aspect_ratio: 4/1
      entities:
        - entity: light.test
        - entity: light.test_2
```

Closing this now!
