### ISSUE TITLE
Option for more-info also for garage/covers

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#151]
Love the addition of more-info for thermostats.

I have two Aeotec Garage controllers, and they only works as a up/down switch for opening garage, that means I can't set it to 50% open.

When I press the button for garage, the popup cover things pops up, but there is no way to control the garage door like that. If that makes sense. I just get an error message that cover.garasje doesn't support that etc from home assistant, here's my config.

```
  garasje:
    icon: mdi:garage
    show_in_favorites: true
    show_in_menu: false
    subtitle: "[[[ if (states['sensor.current_garage_doors_open'].state == 0) return `Alle garasjer lukket; if (states['sensor.current_garage_doors_open'].state == 1) return `1 Garasje åpen`; else return `${states['sensor.current_garage_doors_open'].state} garasjer er åpen`; ]]]"
    button_badge: sensor.current_garage_doors_open
    button_label: "[[[ if (states['sensor.current_garage_doors_open'].state == 0) return `Alle garasjer er lukket`; if (states['sensor.current_garage_doors_open'].state == 1) return `1 Garasje åpen`; else return `${states['sensor.current_garage_doors_open'].state} Garasjer er åpen`; ]]]"
    layout:
      layout:
        card_margin: 4px 8px 8px
        margin: 0px 8px    
    addons:
      button:
        - title: Garasje
          entities:
            - entity: cover.gammel_garasje
              show_label: false
            - entity: cover.garasje
              show_label: false
```

I use show_label: false due to the fact since it can't calculate 0-100% / open/closed it returns undefined. Would love to use more-info here also, because then I get up/down arrows.

**Comment by jimz011** [comment]
Doesn't the settings button take you to the more-info page on the popup?

I don't have covers (yet) so I can't test it properly.

**Comment by bsleep** [comment]
> Love the addition of more-info for thermostats.
> 
> I have two Aeotec Garage controllers, and they only works as a up/down switch for opening garage, that means I can't set it to 50% open.
> 
> When I press the button for garage, the popup cover things pops up, but there is no way to control the garage door like that. If that makes sense. I just get an error message that cover.garasje doesn't support that etc from home assistant, here's my config.
> 
> ```
>   garasje:
>     icon: mdi:garage
>     show_in_favorites: true
>     show_in_menu: false
>     subtitle: "[[[ if (states['sensor.current_garage_doors_open'].state == 0) return `Alle garasjer lukket; if (states['sensor.current_garage_doors_open'].state == 1) return `1 Garasje åpen`; else return `${states['sensor.current_garage_doors_open'].state} garasjer er åpen`; ]]]"
>     button_badge: sensor.current_garage_doors_open
>     button_label: "[[[ if (states['sensor.current_garage_doors_open'].state == 0) return `Alle garasjer er lukket`; if (states['sensor.current_garage_doors_open'].state == 1) return `1 Garasje åpen`; else return `${states['sensor.current_garage_doors_open'].state} Garasjer er åpen`; ]]]"
>     layout:
>       layout:
>         card_margin: 4px 8px 8px
>         margin: 0px 8px    
>     addons:
>       button:
>         - title: Garasje
>           entities:
>             - entity: cover.gammel_garasje
>               show_label: false
>             - entity: cover.garasje
>               show_label: false
> ```
> 
> I use show_label: false due to the fact since it can't calculate 0-100% / open/closed it returns undefined. Would love to use more-info here also, because then I get up/down arrows.

You could use a custom tap/hold action with the switch-popup-card to solve your problem. I'll copy the code I used to solve it. Also, here's a link to the switch-popup-card [https://github.com/DBuit/switch-popup-card](url)

```            
tap_action:
  haptic: light
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
      data:
        title: ' '
        size: fullscreen
        card_mod:
          style:
            .: |
              :host {
                --primary-text-color: AliceBlue !important;
                --margin-top: -40px !important;
              }
              mwc-icon-button {
                color: AliceBlue !important;
              }
        style: |
          --popup-background-color: black !important;
          --popup-header-background-color: var(--popup-background-color) !important;
          --popup-border-radius: 28px !important;
        content:
          type: vertical-stack
          cards:
            - type: custom:switch-popup-card
              fullscreen: false
              noActiveState: ' '
              entity_value_path: state
              entities:
              - cover.garage_opener
              buttons:
              - icon: mdi:garage-open-variant
                value: "open"
                name: "Open"
                color: '#FFF'
                icon_color: rgba(255,255,255,1)
                service: cover.open_cover
                service_data:
                  entity_id: cover.garage_opener
              - icon: mdi:garage-variant
                value: "closed"
                name: "Closed"
                color: '#FFF'
                icon_color: rgba(255,255,255,1)
                service: cover.close_cover
                service_data:
                  entity_id: cover.garage_opener
```

**Comment by jimz011** [comment]
Funny that you mention this, because I already use switch-popup-card in my own setup, I didn't realise that it wasn't in HKI yet. Though I did not make anything useful with it yet other than some alarm panel (as I dislike the keypad).
![image](https://user-images.githubusercontent.com/47046878/208264221-8392a76b-a21c-462a-9b85-82c046f69fe5.png)

So this is a solution to the garage/cover issue that you had?

**Comment by bsleep** [comment]
> Funny that you mention this, because I already use switch-popup-card in my own setup, I didn't realise that it wasn't in HKI yet. Though I did not make anything useful with it yet other than some alarm panel (as I dislike the keypad). ![image](https://user-images.githubusercontent.com/47046878/208264221-8392a76b-a21c-462a-9b85-82c046f69fe5.png)
> 
> So this is a solution to the garage/cover issue that you had?

Sorry, I wasn't the original poster of the issue. I just happened to be looking at the open issues and wanted to help provide a potential fix for the original posters problem. It is how I solved the problem for myself though.

![Screenshot from 2022-12-17 14-47-07](https://user-images.githubusercontent.com/52616844/208265465-5878e02c-1495-4bbc-812b-710a4cb0d7f3.png)


I do have some thoughts around how to potentially solve the problem by maybe setting cover_control to false and modifying the button.yaml in hki-base to select a different popup card.

```
          cards:
            {% if ((device.cover_control is defined) and (device.cover_control == 'false')) %}
            - !include
              - '../templates/popups/covers-notilt-popup.yaml'
              {% if device.entity is defined %}
              - entity: {{ device.entity }}
              {% else %}
              - entity: {{ device }}
              {% endif %}
            {% else %}
            - !include
              - '../templates/popups/covers-popup.yaml'
              {% if device.entity is defined %}
              - entity: {{ device.entity }}
              {% else %}
              - entity: {{ device }}
              {% endif %}
                {% if ((device.cover_control is defined) and (device.cover_control == 'tilt_position')) %}
                cover_control: cover.set_cover_tilt_position
                {% else %}
                cover_control: cover.set_cover_position
                {% endif %}
            {% endif %}
```

Then for the popup card

```
# lovelace_gen

# Cover No Tilt Popup Card
type: custom:switch-popup-card
fullscreen: false
noActiveState: ' '
entity_value_path: state
entities:
- {{ entity }}
buttons:
- icon: mdi:garage-open-variant
  value: "open"
  name: "Open"
  color: '#FFF'
  icon_color: rgba(255,255,255,1)
  service: cover.open_cover
  service_data:
    entity_id: {{ entity }}
- icon: mdi:octagon
  value: "stop"
  name: "Stop"
  color: '#FFF'
  icon_color: rgba(255,255,255,1)
  service: cover.stop_cover
  service_data:
    entity_id: {{ entity }}
- icon: mdi:garage-variant
  value: "closed"
  name: "Closed"
  color: '#FFF'
  icon_color: rgba(255,255,255,1)
  service: cover.close_cover
  service_data:
    entity_id: {{ entity }}
```
