### ISSUE TITLE
show_header field in views.yaml: Boolean has no effect

### ISSUE THREAD

**Issue by toollu** [jimz011/homekit-infused#156]
In a config where the show_header flag is set to false, e.g.:

```
# views.yaml (example with custom subtitle)
  living_room:
    show_header: false
    subtitle: Overview
    icon: mdi:floor-lamp
```

the boolean has no effect, e.g. the header is still shown in the living_room view.

**Comment by jimz011** [comment]
Did you restart after adding this? Secondly, the navigation bar itself doesn't count as the HKI header.

Could you perhaps share a screenshot of what you are seeing?

**Comment by toollu** [comment]
Yes I did restart.

I see this:

![IMG_3816](https://user-images.githubusercontent.com/38591765/165078599-8d1b5a1c-ff35-41ed-895c-4696195cc3f7.PNG)

Although through:

```
  my_view:
    title: All Lights
    show_header: false
    show_in_favorites: true
    show_in_navbar: true
    show_in_menu: true
    icon: mdi:lightbulb
    addons:
    #...
```

the top bar with title and the badges should be hidden unless I misunderstood something.

This is on HKI5 2022.3.0
