### ISSUE TITLE
[NEW Question]menu  not showing

### ISSUE THREAD

**Issue by wedone** [jimz011/homekit-infused#161]
Sorry, translate with Google
###############NEW####################

**HKI5, where are these functions in the picture below？**

![IMG_20220519_014018](https://user-images.githubusercontent.com/1226460/169442978-87772479-a848-4da9-9e2d-96c84601e44e.png)

###############OLD####################
I really don't know what went wrong，is the default, only changed to Chinese

my **hki-user/views/02.menu.yaml**
```YAML
# Menu
menu:
  title: 菜单
  show_in_navbar: true
  show_in_menu: false
  subtitle: "[[[ return `HKI 5 v.${states['sensor.hki_current_version'].state}`; ]]]"
  icon: mdi:apps
  layout:
    layout:
      card_margin: 4px 8px 8px
      margin: 0px 8px
  addons:
    favorites:
      # Small Screens
      - title: 收藏
        view_layout:
          show:
            mediaquery: "(max-width: 350px)"
        columns: 3
      # Larger Screens
      - title: 收藏
        view_layout:
          show:
            mediaquery: "(min-width: 350px)"
        columns: 4
    menu:
      # Small Screens
      - title: 菜单
        view_layout:
          show:
            mediaquery: "(max-width: 350px)"
        columns: 3
      # Larger Screens
      - title: 菜单
        view_layout:
          show:
            mediaquery: "(min-width: 350px)"
        columns: 4
```
![Screenshot_2022-05-18-07-37-09-512_io homeassistant companion android](https://user-images.githubusercontent.com/1226460/168940030-38e173d7-558a-4ecb-a669-73f5faaa272e.jpg)

my **Lovelace**
```
atomic-calendar-revive
button-card
config-template-card
cover-popup-card
light-popup-card
lovelace-auto-entities
lovelace-card-mod
lovelace-card-tools
lovelace-colorfulclouds-weather-card
lovelace-fold-entity-row
lovelace-layout-card
lovelace-more-info-card
lovelace-state-switch
lovelace-text-input-row
lovelace-xiaomi-vacuum-map-card
mini-graph-card
mini-media-player
scheduler-card
search-card
swipe-card
switch-popup-card
vacuum-card
```
my **integrations**
```
browser_mod
colorfulclouds
hacs
lovelace_gen
scheduler
xiaomi_cloud_map_extractor
xiaomi_miot

```
