### ISSUE TITLE
[FR] Add support for applying scenes to button card addon

### ISSUE THREAD

**Issue by veitw** [jimz011/homekit-infused#169]
Hi,

currently one needs to manually configure a tap action for `scene.turn_on` service to apply a scene:
```
      button:
        - title: Szenen
          columns: 3
          entities:
            - name: Durchsicht
              entity: scene.schlafzimmer_durchsicht
              tap_action:
                action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.schlafzimmer_durchsicht
```

This is because button required a `turn_off` service, which is not provided by `scene`.

It would be great if that instead could work by simply listing a `scene.` entity:
```
      button:
        - title: Szenen
          columns: 3
          entities:
            - name: Durchsicht
              entity: scene.schlafzimmer_durchsicht
```

Best regards,
// Veit
