### ISSUE TITLE
Button Addon hold_aktion noch working 

### ISSUE THREAD

**Issue by Blade0001** [jimz011/homekit-infused#174]
I tried to set a hold_aktion to a button card but it's not working. 
My code looks like
 ``` yaml      
 #entities:
          - sensor.sm_bad_heizung_leistung
          - sensor.sm_bad_heizung_leistung
          - entity: sensor.sm_esszimmer_schrank_mi_leistung
            hold_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.steckdose_esszimmer_schrank_mi
```

The logs shows: 

```log
2022-07-12 00:47:32 ERROR (MainThread) [frontend.js.latest.202207070] http://hassio.local:8123/dwains_dashboard/js/dwains-dashboard.js:90:13832 Uncaught TypeError: Cannot read properties of undefined (reading 'popup_cards')
```
