### ISSUE TITLE
Button Addon: shows state last changed when it should not

### ISSUE THREAD

**Issue by drpeppershaker** [jimz011/homekit-infused#182]
`show_last_changed:` is set to `false`. 

Expected result:
Last Changed does not appear on the button

Actual result:
Last changed does indeed appear on the button

Relevant YAML snippet:

```
Garage:
  title: "Garage"
  show_in_favorites: true
  show_in_menu: true
  subtitle: "Beep Beep"
  icon: mdi:garage-variant
  addons:
    button:
      - title: Garage
        entities:
          - entity: light.garage_lights_3
            Name: Garage Lights
          - entity: light.garage_coach_lights_3
            name: Coach Lights
          - entity: binary_sensor.garage_door_button_input
            name: Garage Door
            show_label: false
            popup_style: switch
            show_last_changed: false
            icon: "[[[ if (entity.state == 'on') return `mdi:garage-open-variant`; else return `mdi:garage-variant` ]]]"
            state_display: "[[[ if (entity.state == 'on') return `Open`; else return `Closed` ]]]"
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.garage_door_button
```

Result:

<img width="175" alt="Screen Shot 2022-09-27 at 3 27 54 PM" src="https://user-images.githubusercontent.com/67330126/192623397-9488b468-313c-4afe-b2c2-b9b5ddc8c60e.png">
