### ISSUE TITLE
Issue with base.yaml file

### ISSUE THREAD

**Issue by LucaOnGitHub17** [jimz011/homekit-infused#208]
Hi ya''ll.

So I have homekit infused 5 installed, but after the new update to 2023.4.1, I am getting critical errors, and with those errors, it won't let me show the cards I have set it to show. I've checked studio code server and in the base.yaml file I am getting errors like: `missed comma between flow collection entries`, `bad intention of a mapping entry` and `end of the stream or a document seperator is expected`. I am not that advanced with yaml, so I don't understand the cause of this issue. This all came semingly at random after the update. Does anyone have an idea on how to fix this? I've tried deleting the old base.yaml and replacing it with a fresh one, but it doesn't seem to work. I was still getting the same exact errors. On my dashboard, instead of buttons, I was getting this error:

```
**Cannot read properties of null (reading 'config'**. 
type: custom:button-card
template:
  - hki-default
name: Bedroom
icon: mdi:bed
show_entity_picture: true
size: 25%
lock:
  enabled: false
  unlock: tap
  duration: 5
aspect_ratio: 1/1
label: '&nbsp;'
show_name: true
show_icon: true
show_state: false
show_units: false
show_label: true
show_last_changed: false
tap_action:
  action: navigate
  navigation_path: bedroom
hold_action:
  action: none
  haptic: heavy
double_tap_action:
  action: none
  haptic: heavy
styles:
  icon:
    - color: var(--ha-icon-color)
  name:
    - color: var(--name-color)
  state:
    - color: var(--state-color)
  label:
    - text-transform: var(--label-text-transform)
    - color: var(--label-color)
  lock:
    - color: var(--lock-color)
  grid:
    - grid-template-columns: 1fr
    - grid-template-areas: '"i i" "area area" "n n" "l l" "s s"'
    - grid-template-rows: 1fr 1fr min-content min-content min-content
state:
  - value: 'on'
    spin: false
    styles:
      card:
        - box-shadow: var(--ha-card-box-shadow-active)
        - '-webkit-box-shadow': var(--ha-card-box-shadow-active)
        - '--ha-card-background': var(--ha-card-background-active)
        - opacity: var(--opacity-on)
      icon:
        - color: var(--ha-icon-active-color)
      name:
        - color: var(--name-color-active)
      state:
        - color: var(--state-color-active)
      label:
        - color: var(--label-color-active)
      lock:
        - color: var(--lock-color-active)
  - value: open
    spin: false
    styles:
      card:
        - box-shadow: var(--ha-card-box-shadow-active)
        - '-webkit-box-shadow': var(--ha-card-box-shadow-active)
        - '--ha-card-background': var(--ha-card-background-active)
        - opacity: var(--opacity-on)
      icon:
        - color: var(--ha-icon-active-color)
      name:
        - color: var(--name-color-active)
      state:
        - color: var(--state-color-active)
      label:
        - color: var(--label-color-active)
      lock:
        - color: var(--lock-color-active)
  - value: 'off'
    styles:
      icon:
        - color: var(--ha-icon-color)
      entity_picture:
        - filter: grayscale(100%)
      card:
        - opacity: var(--opacity-off)
      state:
        - color: var(--state-color)
      label:
        - color: var(--label-color)
      lock:
        - color: var(--lock-color-inactive)
  - value: unavailable
    styles:
      card:
        - opacity: var(--opacity-unavailable)
      state:
        - color: var(--color-unavailable)
```

**If anyone knows a fix, please let me know!**
