### ISSUE TITLE
**Title**: Migration from `popup-card` to `browser_mod` causes "No card type configured" error (Core 2024.11.1 / browser_mod 2.3.3)


### ISSUE THREAD

**Issue by 13709780345** [jimz011/homekit-infused#231]
---

### **Describe the issue**  
After migrating legacy `popup-card` implementations to `browser_mod`, the following errors occur:  
- Original error: `custom element doesn't exist：popup-card`  
- Post-migration error: `No card type configured`  

**Affected files**:  
```plaintext
/config/hki-base/base.yaml  
/config/hki-base/templates/button/hki-thermostat.yaml  
/config/hki-base/templates/popups/covers-popup.yaml  
/config/hki-base/templates/popups/light-popup.yaml  
```

### **Steps to reproduce**  
1. Replaced all `popup-card` references with GPT-suggested `browser_mod` implementations  
2. Modified code blocks as shown below  

**Original deprecated code**:  
```yaml
# Example from /config/hki-base/base.yaml
type: custom:popup-card
entity: input_boolean.dummy1
card: ...  # Nested card configuration
```

**Modified implementation**:  
```yaml
# Attempted migration in conditional card
- type: conditional
  conditions:
    - entity: input_boolean.dummy1
      state_not: dummy
  card:
    type: custom:button-card  # Direct button-card usage
    ...  # Style configurations
```

### **Current behavior**  
- ❌ `No card type configured` error persists  
- ❌ Popups fail to render after migration  
- ✅ Other `browser_mod` functionalities work normally  

### **Environment**  
- Home Assistant Core: 2024.11.1  
- Frontend version: 20241106.2  
- browser_mod version: 2.3.3 (via HACS)  
- Browser: N/A (error occurs across multiple devices)  

Has anyone successfully migrated `popup-card` in recent HA versions? Any guidance would be appreciated!
