### ISSUE TITLE
A bit more containment

### ISSUE THREAD

**Issue by righteousbs** [jimz011/homekit-infused#49]
It would be good to keep following HKI code blocks contained within the package for those of us that use multiple dashboards. Suggest placing these blocks within ...packages/homekit_infused/hki_configuration.yaml

```
sensor:
  - platform: time_date
    display_options:
        ....
```
```
lovelace:
  dashboards:
    homekit-infused:
      mode: yaml
      title: Homekit Infused
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: homekit-infused-lovelace.yaml
```
