### ISSUE TITLE
[ISSUE] Notifications not working - "Script Error in Frontend.js"

### ISSUE THREAD

**Issue by sharkyP** [jimz011/homekit-infused#64]
**Description:** 
While the 'all clear' notification works fine the subsequent conditions are throwing a script error in the log

`[frontend.js.latest.202012120] :0:0 Script error.`

My YAML is below and mirrors the example code
```
- type: conditional
  conditions:
    - entity: alarm_control_panel.alarmo
      state: "disarmed"
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - icon: mdi:check-box-outline
      name: All clear, there are no notifications.

- type: conditional
  conditions:
    - entity: alarm_control_panel.alarmo
      state: "armed_home"
    - entity: alarm_control_panel.alarmo
      state: "armed_away"
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - icon: mdi:check-box-outline
      name: Alarm system is active.

```
**Working**
![image](https://user-images.githubusercontent.com/28176100/102479724-60114400-40b3-11eb-90b4-20dde38ffe8c.png)

**Not working** (with error in log [`frontend.js.latest.202012120] :0:0 Script error.`)
![image](https://user-images.githubusercontent.com/28176100/102479634-4112b200-40b3-11eb-819a-b59dd7fa34d2.png)

**HA Version:** 2020.12.1
**Device:** Intel NUC I5 7th Gen, iPhone X, Chrome browser
