### ISSUE TITLE
[FR] Button to call a service with data

### ISSUE THREAD

**Issue by fx-git-fx** [jimz011/homekit-infused#72]
**Is your feature request related to a problem? Please describe.**
I would like to call a service from a button and hand over min. one string or other piece of data to that service

**Describe the solution you'd like**
Call a user defined service so that the service can use the data

**Describe alternatives you've considered**
none

**Additional context**

Definition of the service as an example:
```
daapd_request_queue_add:
  url: 'http://192.168.0.100:3689/api/queue/items/add?uris={{ track_id }}&clear={{ clearlist }}&playback={{ play }}'
  method: POST
  headers:
    authorization: !secret daapd_password
    accept: "application/json, text/html"
    user-agent: 'Mozilla/5.0 {{ useragent }}'
  payload: '{"uris": "{{ track_id }}","clear": "{{ clearlist }}","playback": "{{ play }}}'
  content_type: 'application/json; charset=utf-8'
  verify_ssl: false
```

Call to that service via developer tools in HA (working):
```
service: rest_command.daapd_request_queue_add
data:
  track_id: "library:track:39025"
  clearlist: "true"
  play: "start"
```

I would like to customize the button like this to call that service (this does not work at the moment):
```
        cards:
          - !include
            - '../../../base/templates/button/service-call-with-option.yaml'
            - entity: media_player.forked_daapd_server
              name: 1Live
              service: rest_command.daapd_request_queue_add
              service_data:
                track_id: "library:track:39025"
                clearlist: "true"
                play: "start"
```

One piece of service_data with a generic name would by sufficent :-)
