### ISSUE TITLE
[FR] Reorganize header sensors (4.0.0c)

### ISSUE THREAD

**Issue by deahte** [jimz011/homekit-infused#74]
Would it be possible to allow changing the sensor order in general_config.yaml without needing to change header-base-template.yaml?  I changed mine to light/fan/door/window/motion, however, the popup will reflect the default order in your release.  Easy enough to change manually, but it is needed each version release due to overwriting /hki-base.  I don't mind continuing to do so, but thought I'd check.  Thanks

**Comment by jimz011** [comment]
Well yes in general_config.yaml they are named sensor_1 to sensor_5. If you want sensor 1 to be on the location of sensor 5 put the config there.

in your case
```
sensors:
  sensor_1:
    icon: mdi:fan
    entity: your light groups sensor
    group_entity: (if used) group entity
  sensor_2:
    icon: mdi:fan
```
And so on. Sensor 1 is the most left sensor, sensor 5 the most right. Setting this in this file should make it persistent after updates
