### ISSUE TITLE
Preset Climate to false not working (4.0.0d)

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#81]
```
# CLIMATE
  climate:
    subtitle: "[[[ return `Beneden: ${states['sensor.gem_temp_beneden'].state} | Boven: ${states['sensor.gem_temp_boven'].state} | Buiten: ${states['sensor.gem_temp_buiten'].state} `; ]]]"
    max_columns: 3
    button_columns: 3
    show_subtitle: true
    show_in_navbar: false
    show_in_favorites: true
    show_cool: false
    show_heat: false
    show_set_temperature: false
    icon: mdi:thermometer
    button_badge: sensor.gem_temp_beneden
    climate:
    devices:
      thermostaat:
        - climate.woonkamer
```

Setting the show_cool, show_heat, show_set_temperature to false still displays these buttons in the view.
