### ISSUE TITLE
TypeError '__init__() takes 2 positional arguments but 3 were given'

### ISSUE THREAD

**Issue by ghost** [jimz011/homekit-infused#84]
Hello.
I'm trying to use HKI but i got a type error.
I'm installed all addons. Running on RPI 4, Raspbian Buster. HA 2021.1.5
Here is the full error:

2021-05-09 07:49:08 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2441612048] Error handling message: Unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lovelace/dashboard.py", line 186, in async_load
    self._load_config, force
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lovelace/dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return parse_yaml(conf_file)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/yaml/loader.py", line 73, in parse_yaml
    return yaml.load(content, Loader=SafeLineLoader) or OrderedDict()
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/yaml/loader.py", line 152, in _include_dir_named_yaml
    mapping[filename] = load_yaml(fname)
  File "/home/homeassistant/.homeassistant/custom_components/lovelace_gen/__init__.py", line 37, in load_yaml
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
  File "/srv/homeassistant/lib/python3.7/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/home/homeassistant/.homeassistant/custom_components/lovelace_gen/__init__.py", line 37, in <lambda>
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by jimz011** [comment]
Hi sorry for the late response, I have been tested positive on Covid so I was a bit out the last few days.

This problem is too generic to give you a straight answer. If you could please share your config files (view_config and general_config) as well? Also do you run Dwains Dashboard as a primary/secondary dashboard? If yes you must do a few extra steps.

**Comment by ghost** [comment]
view_config:
```
view_config: # For examples check out https://github.com/jimz011/homekit-infused/tree/4.x.x-personal

# Home
  home:
    title: greeting
    show_in_navbar: true
    show_in_menu: false
    columns: 
      buttons: 4
    favorites:
      show_title: false
    welcome_message: true

  menu:
    show_in_navbar: true
    show_in_menu: false
    icon: mdi:apps
    subtitle: "[[[ return `Homekit Infused Version: ${states['sensor.hki_current_version'].state}`; ]]]"
    search_card:
    favorites: 
    menu: 
    hki_menu:

# You can remove this line and the example views below or continue to build on them.

# Example
  lights:
    icon: mdi:floor-lamp
    show_in_favorites: true
    subtitle: Overview
    devices:
      my_lights:
        - light.my_lamp
```

general_config:
```
general_config:

# Screen Margins
  margins: 7px

# Alarm Entity ##########################################################################################################################
  alarm:
    entity: alarm_control_panel.home_alarm
    type: keypad # Choose between keypad or toggles
      
# Header ################################################################################################################################
  header:
    show_sensors: true 
    sensors: # You can remove the sensors you don't want to show, you can have a maximum of 5 header sensors. Note: Leaving group_entity empty will disable it's popup.
      sensor_1:
        icon: mdi:door
        entity: sensor.current_doors_open
        group_entity: group.all_door_sensor_entities
      sensor_2:
        icon: mdi:window-closed
        entity: sensor.current_windows_open
        group_entity: group.all_window_sensor_entities
      sensor_3:
        icon: mdi:motion-sensor
        entity: sensor.current_binary_sensors_on
        group_entity: group.all_binary_sensor_entities
      sensor_4:
        icon: mdi:power-plug
        entity: sensor.current_devices_on
        group_entity: group.all_device_switch_entities
      sensor_5:
        icon: mdi:lightbulb
        entity: sensor.current_lights_on
        group_entity: group.all_light_entities

# Vacuum Fan Speeds
  vacuum:
    min: Silent
    medium: Standard
    high: Medium
    max: Turbo
    mop: Gentle

## Optional #############################################################################################################################
# Sidebar ###############################################################################################################################
  sidebar:
    sidebar_title: Homekit Infused
    show_clock: true
    show_date: true
```

I didn't changed them after installation
