### ISSUE TITLE
[FR] Adding custom-button with grid functionality

### ISSUE THREAD

**Issue by NewOakley** [jimz011/homekit-infused#90]
Dear, I would like to use the custom-button functionality with a grid option for having a status of my HasSO like in the example of custom-button is used. I would like this button get for some system components, but also for my internet status, my complete network components (router, firewall, switches) and printer statuses. So I think the example HasSO can be reused for a lot of purposes.

I have made some work. The original one as the example is working, only ik would like to have with the current theme (using a new template I guess) and reusing some element of your existing parts of templates. 

Later this afternoon I will add my current code so I think you can use it where needed. My problem now is I would like to pass 4 config_field with using a custum_card = true and my own on file in subdir I would like to included my template. A lot I have already working, but I’m not getting values in my config_fields, some where I’m doing something wrong with the passing value from yaml and using the template.

here is my code:
template to use for system en network statussen in grid:
/hki-user/templates/button/button-card-templates/system-network.yaml

```
# lovelace_gen

# card
type: custom:button-card
template: 
  - style-default
#  - {{ grid|default('default-hki-grid') }}
name: "{{ name }}"
icon: "{{ icon }}"
color: {{ color|default('auto') }}
size: {{ size|default('25%') }}
lock:
  enabled: {{ lock|default('false') }}
  unlock: {{ lock_unlock|default('tap') }}
  duration: {{ lock_duration|default('5') }}
aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "{{ label|default('&nbsp;') }}"
show_name: {{ show_name|default('true') }}
show_icon: {{ show_icon|default('true') }}
show_state: {{ show_state|default('false') }}
show_label: {{ show_label|default('true') }}
show_last_changed: {{ show_last_changed|default('false') }}
styles:
  grid:
    - grid-template-areas: '"i rt" "n n" "l1 l1" "l2 l2" "l3 l3"'
    - grid-template-columns: 1fr 1fr
    - grid-template-rows: 1fr min-content min-content min-content min-content
  name: #
    - justify-self: start
    - padding: 0px 10px
    - font-weight: var(--name-font-weight)
    - font-family: var(--font-family) 
    - font-size: var(--name-font-size)
  img_cell: #
    - align-self: start
    - text-align: start
    - align-items: flex-start
    - justify-content: flex-start
  icon:
    - width: 50%
    - margin-top: -15% 
  custom_fields:
    rt:
      # - align-self: start
      # - justify-self: end
      - background-color: "{{ background_color }}"
      - border-radius: 12px
      - overflow: visible
      - position: absolute
      - right: 7px
      - top: 7px
      - padding: 0px 5px
      - height: 22px
      - min-width: 12px
      - font-size: var(--badge-font-size)
      - line-height: 22px
      - font-weight: var(--badge-font-weight)
      - text-transform: var(--badge-text-transform)
    l1:
      - font-weight: var(--label-font-weight)
      - font-size: var(--label-font-size)
      - font-family: var(--font-family)
      - padding: 0px 10px
      - justify-self: start
    #   # - --text-color-sensor: '[[[ if (states["sensor.processor_usage"].state > 80) return "red"; ]]]'
    l2:
      - font-weight: var(--label-font-weight)
      - font-size: var(--label-font-size)
      - font-family: var(--font-family)
      - padding: 0px 10px
      - justify-self: start
    #   # - --text-color-sensor: '[[[ if (states["sensor.processor_usage"].state > 80) return "red"; ]]]'
    l3:
      - font-weight: var(--label-font-weight)
      - font-size: var(--label-font-size)
      - font-family: var(--font-family)
      - padding: 0px 10px
      - justify-self: start
    #   # - --text-color-sensor: '[[[ if (states["sensor.processor_usage"].state > 80) return "red"; ]]]'
    
custom_fields: 
  rt: "{{ notification|default('rt') }}"
  l1: "{{ cpu|default('line 1') }}"
  l2: "{{ ram|default('line 2') }}"
  l3: "{{ sd|default('line 3') }}"

```
The grid is like the example in HassOS from custom-button exmaple. 
- left top an icon
- right top an attributes [rt in custom_field)
- name, name of the sensor
- line 1 an attribute (l1 in custom_field)
- line 2 an attribute (l2 in custom_field)
- line 3 an attribute (l3 in cusum_field)

For example speedtest:
- custom_field, rt: a sensor attribute the milliseconds are OK
- name: Internet
- l1: DL: xxx.yy 
- l2: UL: xxx.yy 
- l3: Ping: zzzz

view_config:
```
utilities:
    Title: Utilities
    subtitle: 'something to fill in' #"[[[ if (states['sensor.current_scenes_on'].state == 0) return `All scenes are inactive`; if (states['sensor.current_scenes_on'].state == 1) return `1 scene is active`; else return `${states['sensor.current_scenes_on'].state} scenes are active`; ]]]"
    columns: 
      buttons: 4
    icon: mdi:cogs
    button_badge: sensor.current_scenes_on #an exmaple sensor
    show_in_favorites: true
    #button_label: 'boe'
    custom_cards: true
```
i create a view in:
/hki-user/view/utilities/05. Overvier.yaml

```
- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:

      - !include
        - '../../../hki-base/templates/other/title-text.yaml'
        - name: '&nbsp; System States'

      - type: horizontal-stack
        cards:
          - !include
            - '../../../hki-user/templates/button/button-card-templates/system-network.yaml'
            - name: Internet
              entity: sensor.speedtest_ping
              icon: "mdi:speedometer"
              custom_fields:
                rt: >
                    "[[[
                      return `<span> ri ri ri </span>`
                    ]]]"
                l1: "l1 l1 l1"
                l2: "l2 l2 l2"
                l3: "l3 l3 l3"
```
I expected the "ri ri ri", "l1 l1 l1", "l2 l2 l2" "l3 l3 l3" values were passes through the template to fill in the grid. But this doesn't work. I got back 'rt', 'line 1', 'line 2', 'line 3', and those are the default values from the template. Somethingis going wrong here or i set the wrong code in the file.

Hopefully you can implement this as an template and grid button in the next version and fix this part where i got stuck. I shared the code to help you so far i can.

thank you
