### ISSUE TITLE
 v4.0.0e: Battery add-on error

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#92]
```
# Battery
  battery:
    subtitle: Overview
    columns:
      buttons: 4
    icon: mdi:battery-50
    battery:
      columns: 4
```

this simple setting (copied from your personal view_config) gives an error for all battery entities.
<img width="770" alt="Schermafbeelding 2021-05-16 om 18 38 01" src="https://user-images.githubusercontent.com/57673156/118405067-01f28800-b676-11eb-8c41-7b9253f90833.png">

Just for your info a custom view with auto-entities and include - entity_id: '*battery*' worked always well.
