### ISSUE TITLE
[FR] Add attribute to Battery Add-on

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#93]
I have a couple of Hue sensors. These sensor don't have an entity for the battery_level. To get the battery_level there's a workaround with the HACS Attribute Integration. It places the battery_level as an attribute in the light_level entity of the sensor. So to display this battery_level need to use this code in the view:

battery:
      - title: Temperatuur sensoren
        entities:
          - entity: sensor.overloop_boven_light_level
            **attribute: battery_level**
            name: Trap boven

Could you add this to the extra options of the Battery Add-on?

**Comment by E020** [comment]
And supporting this with the entity card would also be nice; MeteoAlarm.eu uses attributes for the weather alarms.

**Comment by jimz011** [comment]
Ah ofc didnt account for the fact that people still use the hue bridge 🤣. Not sure if this is easily possible with button card. But I guess it should be easy enough.

For now you could create a template sensor out of it if you cant wait for the fix 🤣

```
sensor:
  - platform: template
    sensors:
      battery_hue_kitchen:
        value_template: "{{ state_attr('sensor.hue_whatever', 'battery_level') }}"
```
