### ISSUE TITLE
[FR] User Defined Title Sizes

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#99]
It would be great to be able to set the header (the title that is defined above a group of devices) font size from within the general_config.yaml file.

Example of what I mean by header title:
view_config.yaml
```
lights:
  icon: mdi:lightbulb
  show_in_menu: true
  subtitle: Control
  devices:
    - title: Bedroom
      entities:
        - input_boolean.empty
```
^ The title that is defined under the `devices` section. I usually make it much bigger in my own configuration.

Thanks!
